service: nest-serverless-lambda-demo

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  webpack:
    packager: npm
    webpackConfig: 'webpack.config.js'
    includeModules: true

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  environment:
    DATABASE_URL: ${env.DATABASE_URL}
  httpApi:
    cors: true

functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    handler: src/main.handler2
    events:
      - http:
          method: any
          path: /{any+}
